### PR TITLE
make pogy ready to get sharded 🗡️ 

### PR DESCRIPTION
**Pull request by eNtee-bots**
I change some thinks to get Pogy ready to get sharded you can now easy sharding pogy i hope i can help you with this.

mfg. eNtee

### CODE REVIEW

**Comment by ConnorDoesDev** [comment]
Seems pretty good, I'd recommend changing the "shardedbot" variable to "shard" though.

**Comment by eNtee-bots** [comment]
kk

**Comment by eNtee-bots** [comment]
Now i think is all done

**Comment by eNtee-bots** [comment]
i find somthing and thats not good if you want to charge pogy with my edits you cant launch the dashboard i dont know how to fix that so i stop this here

**Pull request closed without merging**
